# Site settings
title: A blog about Nicolas Dionne
description: A blog about me.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nicolas Dionne
user_description: ML Engineer specialized in Computer Vision and tabular data. Proven track record of delivering full-cycle AI solutions, from data strategy and annotation pipelines to R&D for robust model architectures and MLOps. Skilled in transforming experimental models into scalable, production-grade deployments.
user_title: Machine Learning Engineer
email: nicolas.dionne@hotmail.com
linkedin_username: nicolas-dionne-6915451ab
github_username:  NicDionne

user_image: "/assets/img/profile_pic.png"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
